# docker-compose.yml
version: '3.9'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=supersecretkey
      - DATABASE_URL=postgresql://postgres:postgres@auth-db:5432/authdb
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - USER_DATABASE_URL=postgresql://postgres:postgres@user-db:5432/userdb
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  auth_data:
  user_data: