version: '3.9'

services:
  appointment-service:
    build: ./appointment-service
    ports:
      - "8002:8002"
    environment:
      - APPOINTMENT_DATABASE_URL=postgresql://postgres:postgres@appointment-db:5432/appointmentdb
    depends_on:
      - appointment-db

  appointment-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointmentdb
    ports:
      - "5452:5432"
    volumes:
      - appointment_data:/var/lib/postgresql/data

volumes:
  appointment_data:

